name = "Yukkuricraft-Border-of-Magic-and-Tech"
author = "Taiyouh"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86bbbba229d61c138ddf88aee27357c0a659db31309c842ccb091fe4143ad22c"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
