name = "Yukkuricraft-Border-of-Magic-and-Tech"
author = "Taiyouh + Birb!"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7b8d9999a9bafe1d4e4e3d9fb10fa2626d912fb8b6f29a29fb590e5097e8cf3"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
