name = "Yukkuricraft-Border-of-Magic-and-Tech"
author = "Taiyouh + Birb!"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bc5ffd3424fa53dc6f5a51b1f1d0f7370875b0831b2c76c0b163302b21a902f"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
