name = "Yukkuricraft-Border-of-Magic-and-Tech"
author = "Taiyouh"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "959e41bcc56672c1b264e8f5e58ce77ae2e3676fce4f2b177fb162e0c9874a9d"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
