name = "Yukkuricraft-Border-of-Magic-and-Tech"
author = "Taiyouh + Birb!"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07a12181c6706e295cfc6b9d8ec0d647c88851da98703e4ac3d682524644b574"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
