# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.block_entities]

			[light_sources.settings.block_entities.minecraft]
				bed = true
				calibrated_sculk_sensor = true
				furnace = true
				dropper = true
				daylight_detector = true
				sign = true
				jukebox = true
				brewing_stand = true
				sculk_sensor = true
				hanging_sign = true
				brushable_block = true
				conduit = true
				beehive = true
				dispenser = true
				smoker = true
				lectern = true
				skull = true
				campfire = true
				barrel = true
				chest = true
				piston = true
				sculk_shrieker = true
				end_portal = true
				shulker_box = true
				enchanting_table = true
				banner = true
				structure_block = true
				sculk_catalyst = true
				ender_chest = true
				bell = true
				end_gateway = true
				comparator = true
				beacon = true
				command_block = true
				jigsaw = true
				hopper = true
				mob_spawner = true
				chiseled_bookshelf = true
				trapped_chest = true
				decorated_pot = true
				blast_furnace = true

			[light_sources.settings.block_entities.farmersdelight]
				basket = true
				canvas_sign = true
				stove = true
				cutting_board = true
				skillet = true
				cabinet = true
				cooking_pot = true

			[light_sources.settings.block_entities.botania]
				loonium = true
				bellows = true
				daffomill = true
				enchanter = true
				red_string_fertilizer = true
				spectrolus = true
				altar = true
				hydroangeas = true
				hourglass = true
				runic_altar = true
				mana_pylon = true
				narslimmus = true
				hyacidus = true
				crafty_crate = true
				red_string_container = true
				prism = true
				red_string_relay = true
				tangleberrie_chibi = true
				corporea_funnel = true
				mana_flame = true
				fake_air = true
				rannuncarpus_chibi = true
				terra_plate = true
				labellia = true
				corporea_retainer = true
				tiny_potato = true
				red_string_dispenser = true
				orechid = true
				thermalily = true
				spark_changer = true
				corporea_index = true
				manastar = true
				dreadthorn = true
				mana_distributor = true
				fallen_kanade = true
				red_string_interceptor = true
				cell_block = true
				mana_pool = true
				rafflowsia = true
				endoflame = true
				brewery = true
				pump = true
				bellethorn = true
				corporea_crystal_cube = true
				cacophonium_block = true
				avatar = true
				exoflame = true
				hopperhock = true
				agricarnation = true
				ender_eye_block = true
				corporea_interceptor = true
				medumone = true
				vinculotus = true
				animated_torch = true
				clayconia = true
				cocoon = true
				clayconia_chibi = true
				mini_island = true
				rosa_arcana = true
				red_string_comparator = true
				bergamute = true
				jiyuulia_chibi = true
				gourmaryllis = true
				pure_daisy = true
				light_relay = true
				teru_teru_bozu = true
				incense_plate = true
				marimorphosis_chibi = true
				bubbell = true
				tangleberrie = true
				hopperhock_chibi = true
				starfield = true
				dandelifeon = true
				solegnolia = true
				jaded_amaranthus = true
				entropinnyum = true
				gaia_head = true
				bubbell_chibi = true
				kekimurus = true
				marimorphosis = true
				alfheim_portal = true
				shulk_me_not = true
				turntable = true
				jiyuulia = true
				tigerseye = true
				bellethorn_chibi = true
				spectranthemum = true
				platform = true
				rannuncarpus = true
				spawner_claw = true
				tiny_planet_block = true
				pollidisiac = true
				heisei_dream = true
				agricarnation_chibi = true
				forest_eye = true
				mana_fluxfield = true
				open_crate = true
				orechid_ignem = true
				solegnolia_chibi = true
				mana_spreader = true
				munchdew = true
				bifrost = true

			[light_sources.settings.block_entities.arcadiandream]
				danmaku_crafting_table = true
				mysterious_seal = true
				onbashira = true
				ritual_shrine = true

			[light_sources.settings.block_entities.create]
				clockwork_bearing = true
				funnel = true
				hand_crank = true
				simple_kinetic = true
				clipboard = true
				rope_pulley = true
				harvester = true
				display_link = true
				lectern_controller = true
				encased_shaft = true
				item_drain = true
				belt = true
				backtank = true
				chassis = true
				gantry_pinion = true
				steam_engine = true
				clutch = true
				toolbox = true
				fake_track = true
				cuckoo_clock = true
				track_observer = true
				peculiar_bell = true
				motor = true
				pulse_extender = true
				elevator_contact = true
				sequenced_gearshift = true
				crushing_wheel = true
				mechanical_roller = true
				spout = true
				gearbox = true
				stockpile_switch = true
				powered_shaft = true
				andesite_tunnel = true
				stressometer = true
				smart_chute = true
				sticker = true
				encased_large_cogwheel = true
				nixie_tube = true
				water_wheel = true
				mechanical_piston = true
				mechanical_press = true
				bogey = true
				track_signal = true
				smart_fluid_pipe = true
				portable_storage_interface = true
				crushing_wheel_controller = true
				pulse_repeater = true
				mechanical_bearing = true
				depot = true
				schematicannon = true
				chute = true
				sliding_door = true
				fluid_pipe = true
				encased_cogwheel = true
				mechanical_crafter = true
				copycat = true
				cursed_bell = true
				hose_pulley = true
				rotation_speed_controller = true
				creative_crate = true
				basin = true
				encased_fluid_pipe = true
				fluid_valve = true
				brass_tunnel = true
				fluid_tank = true
				schematic_table = true
				portable_fluid_interface = true
				analog_lever = true
				adjustable_chain_gearshift = true
				windmill_bearing = true
				speedometer = true
				millstone = true
				creative_fluid_tank = true
				flap_display = true
				turntable = true
				gantry_shaft = true
				mechanical_arm = true
				item_vault = true
				blaze_heater = true
				flywheel = true
				weighted_ejector = true
				content_observer = true
				deployer = true
				track = true
				track_station = true
				elevator_pulley = true
				saw = true
				drill = true
				valve_handle = true
				mechanical_pump = true
				mechanical_mixer = true
				nozzle = true
				cart_assembler = true
				steam_whistle = true
				large_water_wheel = true
				encased_fan = true
				glass_fluid_pipe = true
				gearshift = true
				contraption_controls = true
				redstone_link = true
				placard = true

			[light_sources.settings.block_entities.cccbridge]
				animatronic_block_entity = true
				scroller_block_entity = true
				target_block_entity = true
				source_block_entity = true
				redrouter_block_entity = true

			[light_sources.settings.block_entities.another_furniture]
				service_bell = true
				drawer = true
				planter_box = true
				shelf = true

			[light_sources.settings.block_entities.sliceanddice]
				slicer = true
				sprinkler = true

			[light_sources.settings.block_entities.computercraft]
				computer_command = true
				computer_advanced = true
				turtle_advanced = true
				printer = true
				wireless_modem_advanced = true
				wired_modem_full = true
				turtle_normal = true
				monitor_advanced = true
				speaker = true
				wireless_modem_normal = true
				computer_normal = true
				monitor_normal = true
				cable = true
				disk_drive = true

			[light_sources.settings.block_entities.railways]
				invisible_mono_bogey = true
				track_coupler = true
				conductor_whistle = true
				bogey = true
				track_switch_brass = true
				invisible_bogey = true
				casing_collision = true
				semaphore = true
				mono_bogey = true
				track_switch_andesite = true
				diesel_smokestack = true

			[light_sources.settings.block_entities.ae2]
				debug_energy_gen = true
				crafting_storage = true
				debug_phantom_node = true
				sky_tank = true
				inscriber = true
				quantum_ring = true
				paint = true
				interface = true
				creative_energy_cell = true
				cable_bus = true
				sky_chest = true
				crafting_unit = true
				wireless_access_point = true
				debug_item_gen = true
				light_detector = true
				pattern_provider = true
				energy_acceptor = true
				condenser = true
				dense_energy_cell = true
				crafting_monitor = true
				vibration_chamber = true
				debug_chunk_loader = true
				spatial_pylon = true
				chest = true
				controller = true
				debug_cube_gen = true
				molecular_assembler = true
				crank = true
				cell_workbench = true
				spatial_io_port = true
				energy_cell = true
				charger = true
				spatial_anchor = true
				growth_accelerator = true
				drive = true
				io_port = true

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				camel = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = false
				snowball = true
				tnt = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				ender_pearl = true
				zombie = true
				item_display = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				block_display = true
				tnt_minecart = true
				zombie_villager = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				cod = true
				snow_golem = true
				witch = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				salmon = true
				vex = true
				wandering_trader = true
				wither_skeleton = true
				piglin_brute = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				shulker_bullet = true
				squid = true
				enderman = true
				dragon_fireball = true
				chicken = true
				sniffer = true
				trader_llama = true
				donkey = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.handcrafted]
				seat = true

			[light_sources.settings.entities.endermanoverhaul]
				savanna_enderman = true
				cave_enderman = true
				desert_enderman = true
				snowy_enderman = true
				swamp_enderman = true

			[light_sources.settings.entities.arcadiandream]
				bubble_bullet = true
				ice_fairy = true
				sunflower_fairy = true
				kunai_bullet = true
				star_bullet = true
				circle_bullet = true
				pellet_bullet = true
				fairy = true
				amulet_bullet = true

			[light_sources.settings.entities.another_furniture]
				seat = true

			[light_sources.settings.entities.creeperoverhaul]
				swamp_creeper = true
				bamboo_creeper = true
				snowy_creeper = true
				badlands_creeper = true
				ocean_creeper = true
				desert_creeper = true
				jungle_creeper = true
				dripstone_creeper = true
				beach_creeper = true
				cave_creeper = true
				hills_creeper = true
				spruce_creeper = true

			[light_sources.settings.entities.railways]
				conductor = true
				benchcart = true
				jukeboxcart = true

			[light_sources.settings.entities.ae2]
				tiny_tnt_primed = true

			[light_sources.settings.entities.illagerinvasion]
				hatchet = true
				archivist = true
				provoker = true
				necromancer = true
				basher = true
				marauder = true

			[light_sources.settings.entities.botania]
				pixie = true
				mana_burst = true
				vine_ball = true
				doppleganger = true
				mana_storm = true
				babylon_weapon = true
				falling_star = true
				pink_wither = true
				thorn_chakram = true
				player_mover = true
				corporea_spark = true
				ender_air = true
				thrown_item = true
				pool_minecart = true
				spark = true
				magic_missile = true
				flame_ring = true
				ender_air_bottle = true
				magic_landmine = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

			[light_sources.settings.entities.apugli]
				custom_area_effect_cloud = true
				custom_projectile = true

			[light_sources.settings.entities.create]
				carriage_contraption = true
				seat = true
				stationary_contraption = true
				contraption = true
				gantry_contraption = true
				super_glue = true
				crafting_blueprint = true
				potato_projectile = true

			[light_sources.settings.entities.origins]
				enderian_pearl = true

			[light_sources.settings.entities.wildlife]
				snail = true
				spicebush_butterfly = true
				koi = true
				bluegill = true
				possum = true
				ladybug = true
				morpho_butterfly = true
				catfish = true
				glow_jellyfish = true
				anteater = true
				hermitcrab = true
				armadillo = true
				glasswing_butterfly = true
				seaurchin = true
				tiger_butterfly = true
				phoebe = true
				seahorse = true
				june_beetle = true
				python = true
				chameleon = true
				hamster = true
				stickbug = true
				milk_snake = true
				grass_snake = true
				bluebird = true
				gecko = true
				hedgehog = true
				deer = true
				rhino_beetle = true
				alligator = true
				bettafish = true
				shrimp = true
				jellyfish = true
				hammerhead_shark = true
				stingray = true
				sanddollar = true
				dragonfly = true
				robin = true
				goldfish = true
				iguana = true
				king_snake = true
				rainbow_trout = true
				staghorn_beetle = true
				sparrow = true
				porcupine = true
				lark = true
				starfish = true
				mantaray = true
				swallow = true
				oriole = true
				flycatcher = true
				ant = true
				monarch_butterfly = true
				prawn = true
				towhee = true
				sunflowerbeetle = true
				goldfinch = true
				badger = true
				wren = true
				horseshoecrab = true
				cricket = true
				clam = true
				spider = true
				ferret = true
				white_eye = true
				crab = true
				meadowlark = true

			[light_sources.settings.entities.ad_astra]
				tier_3_rocket = true
				tier_1_rocket = true
				tier_2_rocket = true
				tier_4_rocket = true

