enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "GAP"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
supplementaries = true
create_new_age = true
mcwdoors = true
mcwfences = true
farmersdelight = true
cccbridge = true
mcwroofs = true
botania = true
chipped = true
suppsquared = true
mcwwindows = true
create = true
extended_drawers = true
another_furniture = true
minecraft = true
mcwlights = true
createaddition = true
mcwpaths = true
railways = true
mcwfurnitures = true
origins = true
mcwbridges = true
bellsandwhistles = true
mcwtrpdoors = true
ae2 = true
sliceanddice = true
milk = true
creeperoverhaul = true
handcrafted = true
mcwholidays = true
computercraft = true
arcadiandream = true
illagerinvasion = true
ad_astra = true
gravestones = true
